# Per https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
- package-ecosystem: "maven"
  directory: "/"
  schedule:
    interval: "monthly"
  reviewers:
  - markewaite
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  reviewers:
  - markewaite
